- name: Azure configuration
  hosts: 127.0.0.1
  connection: local

  tasks:

  - name: Login to azure
    shell: az login -u "{{lookup('env', 'email')}}" -p "{{lookup('env', 'password')}}"
    register: ps

  - debug: 
      var: ps.stdout_lines